/* CVS $Id: $ */
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from aif+.owl 
 * @author Auto-generated by schemagen on 31 Mar 2008 12:35 
 */
public class AIF {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://protege.stanford.edu/aif#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property conclusionFulfilledBy = m_model.createProperty( "http://protege.stanford.edu/aif#conclusionFulfilledBy" );
    
    public static final Property fulfilledBySNode = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilledBySNode" );
    
    public static final Property fulfilsFormPremise = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilsFormPremise" );
    
    public static final Property hasPresumptionDesc = m_model.createProperty( "http://protege.stanford.edu/aif#hasPresumptionDesc" );
    
    public static final Property edgeSNodeFromINode = m_model.createProperty( "http://protege.stanford.edu/aif#edgeSNodeFromINode" );
    
    public static final Property edgeSNodeToContent = m_model.createProperty( "http://protege.stanford.edu/aif#edgeSNodeToContent" );
    
    public static final Property hasPremiseDesc = m_model.createProperty( "http://protege.stanford.edu/aif#hasPremiseDesc" );
    
    public static final Property hasEnd = m_model.createProperty( "http://protege.stanford.edu/aif#hasEnd" );
    
    public static final Property fulfilsLocutionDesc = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilsLocutionDesc" );
    
    public static final Property edgeINodeToSNode = m_model.createProperty( "http://protege.stanford.edu/aif#edgeINodeToSNode" );
    
    public static final Property fulfilsTransitionalInferenceScheme = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilsTransitionalInferenceScheme" );
    
    public static final Property hasPostConditionalDesc = m_model.createProperty( "http://protege.stanford.edu/aif#hasPostConditionalDesc" );
    
    public static final Property premiseFulfilledBy = m_model.createProperty( "http://protege.stanford.edu/aif#premiseFulfilledBy" );
    
    public static final Property hasConclusion = m_model.createProperty( "http://protege.stanford.edu/aif#hasConclusion" );
    
    public static final Property fulfilsScheme = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilsScheme" );
    
    public static final Property hasException = m_model.createProperty( "http://protege.stanford.edu/aif#hasException" );
    
    public static final Property hasStart = m_model.createProperty( "http://protege.stanford.edu/aif#hasStart" );
    
    public static final Property edgeContentFromContent = m_model.createProperty( "http://protege.stanford.edu/aif#edgeContentFromContent" );
    
    public static final Property caNodeAttacks = m_model.createProperty( "http://protege.stanford.edu/aif#caNodeAttacks" );
    
    public static final Property hasConclusionDesc = m_model.createProperty( "http://protege.stanford.edu/aif#hasConclusionDesc" );
    
    public static final Property edgeContentFromSNode = m_model.createProperty( "http://protege.stanford.edu/aif#edgeContentFromSNode" );
    
    public static final Property hasPreConditionalDesc = m_model.createProperty( "http://protege.stanford.edu/aif#hasPreConditionalDesc" );
    
    public static final Property fulfilledBy = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilledBy" );
    
    public static final Property fulfils = m_model.createProperty( "http://protege.stanford.edu/aif#fulfils" );
    
    public static final Property edgeTo = m_model.createProperty( "http://protege.stanford.edu/aif#edgeTo" );
    
    public static final Property entailsPresumptionDesc = m_model.createProperty( "http://protege.stanford.edu/aif#entailsPresumptionDesc" );
    
    public static final Property fulfilledByLNode = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilledByLNode" );
    
    public static final Property fulfilsFormConclusion = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilsFormConclusion" );
    
    public static final Property hasPremise = m_model.createProperty( "http://protege.stanford.edu/aif#hasPremise" );
    
    public static final Property fulfilledByTANode = m_model.createProperty( "http://protege.stanford.edu/aif#fulfilledByTANode" );
    
    public static final Property edgeContentToContent = m_model.createProperty( "http://protege.stanford.edu/aif#edgeContentToContent" );
    
    public static final Property hasDescription = m_model.createProperty( "http://protege.stanford.edu/aif#hasDescription" );
    
    public static final Property argInfoText = m_model.createProperty( "http://protege.stanford.edu/aif#argInfoText" );
    
    public static final Property hasSchemeName = m_model.createProperty( "http://protege.stanford.edu/aif#hasSchemeName" );
    
    public static final Property hasText = m_model.createProperty( "http://protege.stanford.edu/aif#hasText" );
    
    /** <p>Locution node</p> */
    public static final Resource LNode = m_model.createResource( "http://protege.stanford.edu/aif#LNode" );
    
    public static final Resource Content = m_model.createResource( "http://protege.stanford.edu/aif#Content" );
    
    public static final Resource ConflictScheme = m_model.createResource( "http://protege.stanford.edu/aif#ConflictScheme" );
    
    public static final Resource TANode = m_model.createResource( "http://protege.stanford.edu/aif#TANode" );
    
    public static final Resource PostConditionalDesc = m_model.createResource( "http://protege.stanford.edu/aif#PostConditionalDesc" );
    
    public static final Resource CANode = m_model.createResource( "http://protege.stanford.edu/aif#CANode" );
    
    public static final Resource ArgInfo = m_model.createResource( "http://protege.stanford.edu/aif#ArgInfo" );
    
    public static final Resource Scheme = m_model.createResource( "http://protege.stanford.edu/aif#Scheme" );
    
    public static final Resource PremiseDesc = m_model.createResource( "http://protege.stanford.edu/aif#PremiseDesc" );
    
    public static final Resource TransitionalInferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#TransitionalInferenceScheme" );
    
    public static final Resource LocutionDesc = m_model.createResource( "http://protege.stanford.edu/aif#LocutionDesc" );
    
    public static final Resource Premise = m_model.createResource( "http://protege.stanford.edu/aif#Premise" );
    
    public static final Resource Form = m_model.createResource( "http://protege.stanford.edu/aif#Form" );
    
    public static final Resource PresumptiveInferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#PresumptiveInferenceScheme" );
    
    public static final Resource PreConditionalDesc = m_model.createResource( "http://protege.stanford.edu/aif#PreConditionalDesc" );
    
    public static final Resource RuleScheme = m_model.createResource( "http://protege.stanford.edu/aif#RuleScheme" );
    
    public static final Resource PresumptivePreferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#PresumptivePreferenceScheme" );
    
    public static final Resource PresumptionDesc = m_model.createResource( "http://protege.stanford.edu/aif#PresumptionDesc" );
    
    public static final Resource Conclusion = m_model.createResource( "http://protege.stanford.edu/aif#Conclusion" );
    
    public static final Resource PreferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#PreferenceScheme" );
    
    public static final Resource PANode = m_model.createResource( "http://protege.stanford.edu/aif#PANode" );
    
    public static final Resource DeductiveInferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#DeductiveInferenceScheme" );
    
    public static final Resource INode = m_model.createResource( "http://protege.stanford.edu/aif#INode" );
    
    public static final Resource RANode = m_model.createResource( "http://protege.stanford.edu/aif#RANode" );
    
    public static final Resource LogicalPreferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#LogicalPreferenceScheme" );
    
    public static final Resource InductiveInferenceScheme = m_model.createResource( "http://protege.stanford.edu/aif#InductiveInferenceScheme" );
    
    public static final Resource Node = m_model.createResource( "http://protege.stanford.edu/aif#Node" );
    
    public static final Resource SNode = m_model.createResource( "http://protege.stanford.edu/aif#SNode" );
    
    public static final Resource ConclusionDesc = m_model.createResource( "http://protege.stanford.edu/aif#ConclusionDesc" );
    
}
