/* CVS $Id: $ */
//package aifowl; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from araucaria4.owl 
 * @author Auto-generated by schemagen on 17 Jul 2008 15:07 
 */
public class ARAUCARIA4 {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/araucaria4#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property toNode = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#toNode" );
    
    public static final Property belongsToScheme = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#belongsToScheme" );
    
    public static final Property hasRole = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#hasRole" );
    
    public static final Property ofVertex = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#ofVertex" );
    
    public static final Property fromNode = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#fromNode" );
    
    public static final Property hasCQAnswer = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#hasCQAnswer" );
    
    public static final Property cqText = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#cqText" );
    
    public static final Property locationX = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#locationX" );
    
    public static final Property textFontName = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#textFontName" );
    
    public static final Property visible = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#visible" );
    
    public static final Property textBoundsStart = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#textBoundsStart" );
    
    public static final Property textBoundsEnd = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#textBoundsEnd" );
    
    public static final Property linkedArgDistance = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#linkedArgDistance" );
    
    public static final Property schemeColorRed = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#schemeColorRed" );
    
    public static final Property supportLabel = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#supportLabel" );
    
    public static final Property owner = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#owner" );
    
    public static final Property refutation = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#refutation" );
    
    public static final Property cqAnswered = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#cqAnswered" );
    
    public static final Property schemeColorAlpha = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#schemeColorAlpha" );
    
    public static final Property extentEnd = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#extentEnd" );
    
    public static final Property schemeColorBlue = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#schemeColorBlue" );
    
    public static final Property roleElement = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#roleElement" );
    
    public static final Property vertexId = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#vertexId" );
    
    public static final Property textFontStyle = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#textFontStyle" );
    
    public static final Property selectedPointY = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#selectedPointY" );
    
    public static final Property textFontSize = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#textFontSize" );
    
    public static final Property visited = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#visited" );
    
    public static final Property schemeColorGreen = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#schemeColorGreen" );
    
    public static final Property diagramFontStyle = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#diagramFontStyle" );
    
    public static final Property diagramFontSize = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#diagramFontSize" );
    
    public static final Property endVertexId = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#endVertexId" );
    
    public static final Property diagramFontName = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#diagramFontName" );
    
    public static final Property text = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#text" );
    
    public static final Property selectedPointX = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#selectedPointX" );
    
    public static final Property inSchemeName = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#inSchemeName" );
    
    public static final Property hidingChildren = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#hidingChildren" );
    
    public static final Property startVertexId = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#startVertexId" );
    
    public static final Property roleClass = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#roleClass" );
    
    public static final Property missing = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#missing" );
    
    public static final Property locationY = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#locationY" );
    
    public static final Property leafCount = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#leafCount" );
    
    public static final Property extentStart = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#extentStart" );
    
    public static final Property inSchemeId = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#inSchemeId" );
    
    public static final Property nodeLabel = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#nodeLabel" );
    
    public static final Property schemeName = m_model.createProperty( "http://www.owl-ontologies.com/araucaria4#schemeName" );
    
    public static final Resource ArauEdgeINodetoSNode = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#ArauEdgeINodetoSNode" );
    
    public static final Resource PropertyWigmore = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#PropertyWigmore" );
    
    public static final Resource PropertyPollock = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#PropertyPollock" );
    
    public static final Resource ArauEdgeSNodetoSNode = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#ArauEdgeSNodetoSNode" );
    
    /** <p>General properties of the diagram.</p> */
    public static final Resource ArauInfo = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#ArauInfo" );
    
    public static final Resource PropertyGraph = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#PropertyGraph" );
    
    public static final Resource Role = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#Role" );
    
    public static final Resource ArauEdgeINodetoINode = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#ArauEdgeINodetoINode" );
    
    public static final Resource InScheme = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#InScheme" );
    
    public static final Resource PropertyToulmin = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#PropertyToulmin" );
    
    public static final Resource ArauEdgeSNodetoINode = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#ArauEdgeSNodetoINode" );
    
    public static final Resource PropertyBase = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#PropertyBase" );
    
    public static final Resource ArauEdge = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#ArauEdge" );
    
    public static final Resource PropertyAif = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#PropertyAif" );
    
    public static final Resource CQAnswer = m_model.createResource( "http://www.owl-ontologies.com/araucaria4#CQAnswer" );
    
}
